### ISSUE TITLE
Support for phpstan 0.12

### ISSUE THREAD

**Issue by snapshotpl** [thecodingmachine/phpstan-safe-rule#17]
Is it possible to add phpstan 0.12 support to v0.1 branch instead of only 1.0-beta?

**Comment by moufmouf** [comment]
Hey @snapshotpl ,

It is of course possible, but it is a bit more work to support both versions (it is not as simple as adding support for both versions in composer.json)
Out of curiosity, are you having troubles  upgrading to "1.0-beta"?
What issues are you facing (both versions should be very very close, with only a few Safe functions added: https://github.com/thecodingmachine/safe/releases/tag/v1.0.0-beta1)

**Comment by snapshotpl** [comment]
@moufmouf because of this https://github.com/infection/infection/pull/885

**Comment by simPod** [comment]
To workaround it, I require `0.1.16 as 1.0-beta1` in my libraries.

**Comment by snapshotpl** [comment]
Since infection support stable `safe` can we also release this lib as stable?

**Comment by moufmouf** [comment]
Since Safe added support for DateTime objects, I just need to add support for detecting calls to "new DateTime" and "new DateTimeImmutable" before releasing a stable version of this lib.
Just a bit more patience :)

**Comment by moufmouf** [comment]
...aaand it's done! :) Let's tag this.

**Comment by moufmouf** [comment]
Closing this issue since infection has migrated.
