### ISSUE TITLE
False positive for `substr()`

### ISSUE THREAD

**Issue by jrmajor** [thecodingmachine/phpstan-safe-rule#27]
> substr(), mb_substr(), iconv_substr() and grapheme_substr() now consistently clamp out-of-bounds offsets to the string boundary. Previously, false was returned instead of the empty string in some cases.

According to PHP 8.0 [migration guide](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.standard), calls to these four functions should no longer trigger PHPStan errors on PHP >=8.

**Comment by dbrekelmans** [comment]
This should be resolved by https://github.com/thecodingmachine/phpstan-safe-rule/pull/28 as it uses a safe 2.0 if you are running php8
