### ISSUE TITLE
Possibility to exclude specific replacement suggestions?

### ISSUE THREAD

**Issue by rgasch** [thecodingmachine/phpstan-safe-rule#30]
When running phpstan with this rule, it (rightly so) flags all instances of unsafe PHP functions. However, in certain instances, this is slightly overzealous, as there are instances where using the default PHP functions is just fine. Is it somehow possible to prevent this reporting in specific instances via some sort of annotation (or some other trick)?

**Comment by dbrekelmans** [comment]
Hi @rgasch, I think the built-in way to ignore errors in phpstan should be sufficient: https://phpstan.org/user-guide/ignoring-errors

Let me know if this resolves your issue.

**Comment by rgasch** [comment]
Yes, this completely resolves my issue, thank you. Sorry for the spam post, my first time using phpstan on an age-old codebase.
