### ISSUE TITLE
Support for PHPStan 2?

### ISSUE THREAD

**Issue by mfn** [thecodingmachine/phpstan-safe-rule#34]
phpstan 2.0 was just released:
- https://github.com/phpstan/phpstan/releases/tag/2.0.0
- https://phpstan.org/blog/phpstan-2-0-released-level-10-elephpants
- Upgrade guide: https://github.com/phpstan/phpstan/blob/2.0.x/UPGRADING.md

**Comment by freddytqg** [comment]
@moufmouf tagging you since you merged some of the last PRs. Master branch seams to work with phpstan 2, is there just a release missing?

**Comment by OskarStark** [comment]
friendly ping @moufmouf

**Comment by moufmouf** [comment]
Tagged! https://github.com/thecodingmachine/phpstan-safe-rule/releases/tag/v1.3.0

Thanks for the friendly ping and the PR guys!

@OskarStark don't hesitate to tag releases if you want. I also made you maintainer of this package.
