### ISSUE TITLE
PHPStan complains when passing object with __toString() as arg into sprinf

### ISSUE THREAD

**Issue by simPod** [thecodingmachine/phpstan-safe-rule#4]
> Parameter #2 $args of function Safe\sprintf expects float|int|string|null, Object\With\ToString\Implemented given.

When `\sprinft` used, it works just fine so I guess there is some extension needed? Thanks!

**Comment by moufmouf** [comment]
Interesting... I'm suspecting this problem might not only be restricted to sprintf but might arise with all functions taking strings as a parameter.

I'll take a look.

**Comment by simPod** [comment]
Ur the best!

**Comment by OskarStark** [comment]
@simPod is this by any chance already fixed?

**Comment by simPod** [comment]
Possible, let's close. I've removed Safe from my projects already, it was kinda inactive for few years 🙃
